version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: telegram_bot_db
    environment:
      POSTGRES_DB: telegram_bot_db
      POSTGRES_USER: telegram_bot_user
      POSTGRES_PASSWORD: telegram_bot_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - telegram_bot_network

  # Uncomment to run the bot in Docker as well
  # telegram_bot:
  #   build: .
  #   container_name: telegram_bot_app
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgresql://telegram_bot_user:telegram_bot_password@postgres:5432/telegram_bot_db
  #   env_file:
  #     - .env
  #   networks:
  #     - telegram_bot_network
  #   restart: unless-stopped

volumes:
  postgres_data:

networks:
  telegram_bot_network:
    driver: bridge